### ISSUE TITLE
Adding proxy & Tor support like sherlock

### ISSUE THREAD

**Issue by crimson-med** [soxoj/maigret#514]
Maigret works very similarly to https://github.com/sherlock-project/sherlock

Adding proxy and tor support could be useful

**Comment by soxoj** [comment]
Maigret already has support of proxy with `--proxy` [argument](https://github.com/soxoj/maigret/blob/main/maigret/maigret.py#L229). But I don't see info about it in the [documentation](https://maigret.readthedocs.io/en/latest/), I will fix it.

Maigret doesn't have `--tor` argument because I think it is more correct to abstract from Tor as an instrument and to use its proxy: `--proxy socks5://localhost:9150`.

Also I should notice that Maigret [supports](https://github.com/soxoj/maigret/blob/main/maigret/maigret.py#L239) `--tor-proxy` for sites only available with Tor.
